// HARZ-Reasoner-1.2 weights — generated by trainer.js run RUN-61bb5b50c588
// dataset HARZ-TRAIN-v1.0 digest 9bb398ffa4900c00c66881006ee61400 | weights digest afb246f06917ff001da0570057c43800
// DO NOT hand-edit: regenerate via learning/train-1-2.mjs
export default {
 "version": "1.2",
 "corpus_index_digest": "b9395e5388a45320dab33ca0f5860c393374bba7e17c54f8b3075653d2042bed",
 "train_dataset": "HARZ-TRAIN-v1.0",
 "train_dataset_digest": "9bb398ffa4900c00c66881006ee61400",
 "stopwords": [
  "what",
  "who",
  "when",
  "where",
  "why",
  "how",
  "is",
  "are",
  "was",
  "were",
  "does",
  "do",
  "did",
  "the",
  "a",
  "an",
  "of",
  "for",
  "to",
  "in",
  "on",
  "at",
  "by",
  "with",
  "and",
  "or",
  "which",
  "that",
  "this",
  "their",
  "its",
  "my",
  "your",
  "tell",
  "list",
  "name",
  "give",
  "show",
  "me",
  "us",
  "please",
  "current",
  "right",
  "now"
 ],
 "function_words": [
  "what",
  "who",
  "when",
  "where",
  "why",
  "how",
  "is",
  "are",
  "was",
  "were",
  "does",
  "do",
  "did",
  "the",
  "a",
  "an",
  "of",
  "for",
  "to",
  "in",
  "on",
  "at",
  "by",
  "with",
  "and",
  "or",
  "which",
  "that",
  "this",
  "their",
  "its",
  "my",
  "your",
  "tell",
  "list",
  "name",
  "give",
  "show",
  "me",
  "us",
  "please",
  "current",
  "right",
  "now",
  "harz"
 ],
 "role_words": [
  "cfo",
  "cto",
  "ceo",
  "coo",
  "founder",
  "cofounder",
  "owner",
  "president",
  "director",
  "chairman",
  "governor",
  "manager",
  "head"
 ],
 "idf": {
  "100": 3.0513,
  "108": 4.9558,
  "137": 4.9558,
  "256": 4.9558,
  "300": 4.9558,
  "330": 3.8712,
  "999": 4.9558,
  "2023": 4.9558,
  "2026": 2.9245,
  "7701": 3.5904,
  "8592": 4.9558,
  "9654": 4.9558,
  "19625": 4.9558,
  "321424": 4.9558,
  "harzswap": 2.472,
  "sovereign": 4.9558,
  "dex": 3.1987,
  "harz": 0.7228,
  "chain": 2.0027,
  "everything": 4.2697,
  "trades": 4.9558,
  "our": 4.2697,
  "public": 4.9558,
  "constant": 4.9558,
  "product": 4.2697,
  "fee": 3.8712,
  "world": 2.9245,
  "market": 3.1987,
  "prices": 3.8712,
  "policy": 4.9558,
  "harzcoin": 4.9558,
  "set": 4.2697,
  "explorer": 4.2697,
  "proof": 3.5904,
  "edge": 2.0857,
  "evm": 4.9558,
  "compatible": 4.9558,
  "sha": 4.9558,
  "overview": 2.5455,
  "blocks": 4.2697,
  "transactions": 4.2697,
  "validators": 4.9558,
  "contracts": 2.7147,
  "add": 4.2697,
  "metamask": 4.2697,
  "root": 4.9558,
  "own": 3.8712,
  "nameserver": 4.9558,
  "the": 1.5709,
  "namespace": 4.9558,
  "one": 2.626,
  "law": 4.9558,
  "zone": 4.9558,
  "canonical": 4.9558,
  "names": 4.9558,
  "height": 3.3742,
  "hash": 4.9558,
  "e94b9693e94a229065f7": 4.9558,
  "signature": 4.9558,
  "ed25519": 4.9558,
  "valid": 4.9558,
  "sign": 3.3742,
  "cloud": 2.0027,
  "first": 2.8134,
  "consolidated": 4.2697,
  "infrastructure": 2.7147,
  "home": 2.8134,
  "gdeg": 2.626,
  "neural": 3.1987,
  "nefi": 3.3742,
  "insure": 3.1987,
  "gov": 2.8134,
  "haeg": 2.8134,
  "hni": 2.8134,
  "energy": 2.7147,
  "inventory": 2.8134,
  "buy": 2.5455,
  "nrl": 2.626,
  "super": 2.3418,
  "clo": 4.2697,
  "faucet": 4.2697,
  "claim": 3.8712,
  "free": 3.1987,
  "tokens": 3.8712,
  "part": 3.3742,
  "ecosystem": 2.4044,
  "app": 2.5455,
  "wallet": 2.2294,
  "exchange": 3.0513,
  "block": 3.5904,
  "circulating": 4.9558,
  "wallets": 3.5904,
  "per": 3.8712,
  "walle": 4.9558,
  "bridge": 3.3742,
  "cross": 4.2697,
  "polygon": 3.5904,
  "status": 3.0513,
  "operational": 4.9558,
  "api": 2.2294,
  "key": 3.8712,
  "required": 4.9558,
  "req": 4.9558,
  "min": 4.9558,
  "coin": 4.2697,
  "machine": 3.8712,
  "turn": 4.2697,
  "contract": 3.3742,
  "address": 3.5904,
  "into": 3.8712,
  "real": 2.472,
  "mint": 4.2697,
  "new": 2.9245,
  "straight": 4.9558,
  "onto": 4.9558,
  "hrc": 4.9558,
  "coins": 3.8712,
  "live": 2.1785,
  "every": 3.3742,
  "gets": 4.9558,
  "rpc": 3.5904,
  "proxy": 3.5904,
  "json": 2.626,
  "gateway": 2.8134,
  "for": 1.9644,
  "mined": 4.9558,
  "endpoints": 2.7147,
  "post": 3.5904,
  "eth": 3.8712,
  "methods": 3.8712,
  "get": 2.3418,
  "health": 3.1987,
  "servi": 4.9558,
  "miner": 4.9558,
  "cron": 4.9558,
  "automated": 4.2697,
  "mining": 3.8712,
  "scheduler": 4.9558,
  "version": 3.5904,
  "balance": 4.2697,
  "000": 3.3742,
  "total": 2.7147,
  "service": 2.9245,
  "governance": 4.2697,
  "community": 4.2697,
  "pilot": 4.2697,
  "voice": 2.9245,
  "honest": 4.2697,
  "disclosure": 4.2697,
  "votes": 4.9558,
  "are": 2.8134,
  "advisory": 4.9558,
  "admin": 3.8712,
  "pay": 2.8134,
  "query": 4.9558,
  "access": 3.8712,
  "agents": 3.1987,
  "available": 3.5904,
  "users": 3.5904,
  "queries": 4.9558,
  "today": 3.8712,
  "revenue": 2.1785,
  "pricing": 4.2697,
  "plans": 4.9558,
  "you": 3.1987,
  "commitment": 4.9558,
  "top": 4.2697,
  "credits": 4.9558,
  "use": 4.9558,
  "anyti": 4.9558,
  "payment": 3.5904,
  "unified": 4.2697,
  "paystack": 3.5904,
  "uba": 4.2697,
  "usdt": 4.2697,
  "history": 4.9558,
  "rates": 4.2697,
  "amount": 4.2697,
  "ngn": 3.3742,
  "method": 4.2697,
  "card": 4.2697,
  "bank": 3.3742,
  "transfer": 3.8712,
  "secure": 4.9558,
  "multi": 3.5904,
  "currency": 4.2697,
  "payments": 3.3742,
  "create": 2.7147,
  "name": 2.2837,
  "customer": 3.8712,
  "email": 3.3742,
  "store": 2.626,
  "marketplace": 2.9245,
  "instant": 3.5904,
  "delivery": 4.2697,
  "knowledge": 4.9558,
  "bundle": 4.2697,
  "engineering": 4.9558,
  "science": 4.9558,
  "commerce": 4.2697,
  "marketing": 4.2697,
  "four": 4.9558,
  "foundations": 4.9558,
  "book": 3.8712,
  "with": 2.5455,
  "day": 4.2697,
  "plan": 4.2697,
  "onboarding": 4.9558,
  "account": 3.0513,
  "all": 2.472,
  "platforms": 2.7147,
  "signup": 4.9558,
  "your": 2.2294,
  "gives": 4.2697,
  "network": 2.1785,
  "pwas": 4.9558,
  "platform": 2.472,
  "self": 4.2697,
  "serve": 4.9558,
  "advertising": 4.9558,
  "campaigns": 4.2697,
  "impressions": 4.9558,
  "launch": 4.9558,
  "campaign": 4.2697,
  "only": 3.5904,
  "harzmusic": 4.9558,
  "amm": 4.9558,
  "swaps": 4.9558,
  "settle": 4.9558,
  "ledger": 4.9558,
  "jobs": 4.9558,
  "abuja": 3.5904,
  "job": 4.2697,
  "board": 4.9558,
  "nigerias": 4.9558,
  "capital": 4.9558,
  "employers": 4.9558,
  "active": 3.0513,
  "technology": 4.9558,
  "finance": 4.9558,
  "healthcare": 4.2697,
  "education": 4.9558,
  "construction": 4.2697,
  "ecp": 4.9558,
  "shutdown": 4.9558,
  "economy": 3.5904,
  "economic": 3.5904,
  "continuity": 4.9558,
  "protocol": 2.472,
  "demo": 4.9558,
  "sandbox": 4.9558,
  "value": 3.5904,
  "money": 4.2697,
  "settlement": 4.2697,
  "queued": 4.9558,
  "needs": 4.9558,
  "unmutant": 4.9558,
  "join": 3.8712,
  "second": 4.9558,
  "internet": 3.5904,
  "not": 3.3742,
  "dead": 4.9558,
  "off": 4.9558,
  "human": 4.2697,
  "steps": 4.9558,
  "open": 4.2697,
  "invoice": 4.9558,
  "send": 2.9245,
  "invoices": 4.9558,
  "paid": 3.5904,
  "via": 3.1987,
  "business": 3.8712,
  "phone": 2.3418,
  "client": 3.8712,
  "optional": 3.5904,
  "due": 4.9558,
  "date": 4.9558,
  "items": 4.9558,
  "genesis": 4.9558,
  "hospital": 4.9558,
  "management": 3.8712,
  "system": 3.8712,
  "patients": 4.9558,
  "appointments": 4.2697,
  "billing": 4.2697,
  "pharmacy": 4.2697,
  "labs": 4.9558,
  "staff": 4.9558,
  "register": 4.9558,
  "patient": 4.9558,
  "age": 4.9558,
  "gender": 4.9558,
  "male": 4.9558,
  "female": 4.9558,
  "condition": 4.9558,
  "place": 4.9558,
  "crypto": 3.8712,
  "blockchain": 3.8712,
  "built": 4.2697,
  "nigeria": 3.8712,
  "powered": 3.0513,
  "cloudflare": 3.0513,
  "wholesale": 4.9558,
  "reseller": 4.9558,
  "hosting": 4.9558,
  "white": 4.2697,
  "label": 4.2697,
  "sites": 4.9558,
  "pwa": 3.8712,
  "login": 4.2697,
  "log": 3.8712,
  "monetize": 4.2697,
  "products": 4.2697,
  "across": 3.3742,
  "crm": 4.2697,
  "starter": 4.9558,
  "manage": 4.2697,
  "customers": 4.9558,
  "basic": 4.2697,
  "reports": 4.2697,
  "month": 4.2697,
  "pro": 4.9558,
  "unlimited": 4.9558,
  "advanced": 4.2697,
  "analytics": 4.2697,
  "sms": 2.8134,
  "bulk": 4.9558,
  "sent": 3.5904,
  "contacts": 4.2697,
  "message": 3.5904,
  "recipients": 4.2697,
  "comma": 4.2697,
  "separated": 4.2697,
  "telecom": 2.472,
  "smpp": 3.8712,
  "build": 3.5904,
  "otp": 3.8712,
  "airtime": 4.9558,
  "apis": 3.8712,
  "nigerian": 3.5904,
  "businesses": 4.2697,
  "compute": 4.2697,
  "operator": 4.9558,
  "calling": 4.2697,
  "esim": 4.9558,
  "pops": 4.9558,
  "view": 4.9558,
  "docs": 4.2697,
  "sendcha": 4.9558,
  "verify": 4.2697,
  "verification": 4.9558,
  "number": 3.8712,
  "purpose": 4.9558,
  "code": 3.5904,
  "outbound": 4.9558,
  "sender": 4.2697,
  "workers": 3.3742,
  "tcp": 4.9558,
  "role": 4.9558,
  "arm": 4.9558,
  "dashboard": 2.7147,
  "noc": 4.2697,
  "incoming": 4.9558,
  "call": 4.9558,
  "dismiss": 4.9558,
  "virtual": 4.9558,
  "data": 3.1987,
  "ussd": 4.2697,
  "hlr": 3.8712,
  "digital": 2.7147,
  "services": 2.8134,
  "africa": 3.5904,
  "builds": 4.9558,
  "vertically": 4.9558,
  "integrated": 4.9558,
  "workforce": 3.8712,
  "and": 2.1785,
  "operations": 4.9558,
  "center": 4.9558,
  "locations": 4.9558,
  "core": 4.2697,
  "distributed": 4.9558,
  "cities": 4.9558,
  "worldwide": 4.9558,
  "online": 3.5904,
  "smsc": 3.8712,
  "rat": 4.9558,
  "ss7": 4.9558,
  "renter": 4.9558,
  "sessions": 4.2697,
  "routed": 4.9558,
  "billed": 4.9558,
  "test": 3.1987,
  "rate": 4.9558,
  "session": 4.9558,
  "e2e": 4.9558,
  "passed": 4.9558,
  "mtn": 4.9558,
  "runs": 4.2697,
  "towers": 4.9558,
  "entire": 4.9558,
  "routing": 4.9558,
  "locat": 4.9558,
  "oracle": 3.3742,
  "prediction": 4.9558,
  "feeds": 4.9558,
  "based": 4.9558,
  "native": 3.8712,
  "price": 3.8712,
  "markets": 4.2697,
  "triggers": 4.9558,
  "positions": 4.9558,
  "loading": 2.4044,
  "skyeye": 4.2697,
  "satellite": 3.8712,
  "feature": 3.8712,
  "phones": 3.3742,
  "apps": 4.2697,
  "any": 3.5904,
  "invention": 4.9558,
  "try": 4.9558,
  "simulato": 4.9558,
  "registry": 4.9558,
  "chains": 4.9558,
  "naira": 4.2697,
  "browser": 4.2697,
  "keys": 3.5904,
  "never": 3.8712,
  "leave": 4.2697,
  "this": 3.5904,
  "device": 3.8712,
  "portfolio": 4.2697,
  "swap": 3.3742,
  "ure": 3.5904,
  "evolve": 3.3742,
  "nexus": 3.5904,
  "forge": 3.3742,
  "dna": 3.5904,
  "maganu": 3.5904,
  "estate": 3.3742,
  "symphony": 3.5904,
  "bull": 3.3742,
  "proto": 4.9558,
  "autonomous": 4.2697,
  "grid": 3.8712,
  "insur": 4.9558,
  "otc": 4.9558,
  "sell": 4.9558,
  "desk": 4.9558,
  "usd": 3.8712,
  "chart": 4.2697,
  "trade": 4.2697,
  "p2p": 4.9558,
  "from": 2.9245,
  "operating": 3.8712,
  "defi": 4.9558,
  "single": 4.9558,
  "infrastru": 4.9558,
  "manifest": 2.7147,
  "short": 2.8134,
  "start": 2.8134,
  "url": 2.8134,
  "display": 2.8134,
  "standalone": 2.8134,
  "background": 3.0513,
  "color": 3.0513,
  "f0f2f5": 3.0513,
  "theme": 3.1987,
  "icons": 3.5904,
  "src": 3.5904,
  "image": 4.2697,
  "svg": 3.8712,
  "f0f2": 4.9558,
  "atomic": 4.9558,
  "bridgeless": 4.9558,
  "two": 4.9558,
  "directly": 4.2697,
  "holds": 4.9558,
  "funds": 4.9558,
  "r14": 4.9558,
  "checks": 4.2697,
  "both": 4.9558,
  "sides": 4.9558,
  "executes": 4.9558,
  "legs": 4.9558,
  "once": 4.2697,
  "rolls": 4.9558,
  "back": 4.2697,
  "description": 3.3742,
  "addresses": 4.9558,
  "bac": 4.9558,
  "agent": 3.8712,
  "deploy": 3.3742,
  "whatsapp": 3.0513,
  "telegram": 3.8712,
  "creators": 4.9558,
  "deploys": 4.9558,
  "browse": 4.9558,
  "publish": 4.9558,
  "builder": 3.8712,
  "streams": 4.2697,
  "categories": 4.2697,
  "hybrid": 4.9558,
  "projects": 4.9558,
  "transaction": 4.9558,
  "engine": 3.0513,
  "lifecycle": 4.9558,
  "calculator": 4.9558,
  "model": 4.9558,
  "big": 4.9558,
  "shift": 4.9558,
  "city": 4.9558,
  "tenancy": 4.2697,
  "sale": 4.9558,
  "consultancy": 4.9558,
  "legaldoc": 4.9558,
  "templates": 3.8712,
  "ndpa": 4.9558,
  "clauses": 4.9558,
  "amp": 4.2697,
  "escrow": 4.2697,
  "phase": 4.2697,
  "venture": 4.9558,
  "ventures": 4.9558,
  "opportunity": 4.2697,
  "est": 4.9558,
  "profit": 4.9558,
  "discover": 4.9558,
  "execution": 4.9558,
  "how": 3.5904,
  "works": 3.3742,
  "vent": 4.9558,
  "enterprise": 4.9558,
  "architecture": 4.9558,
  "prepared": 4.9558,
  "sterling": 4.9558,
  "innovation": 4.9558,
  "compliance": 4.9558,
  "teams": 4.9558,
  "cac": 4.9558,
  "tin": 4.9558,
  "assistant": 4.9558,
  "triage": 4.9558,
  "clinics": 4.9558,
  "profile": 4.9558,
  "reminders": 4.9558,
  "symptom": 4.9558,
  "describe": 4.9558,
  "symptoms": 4.9558,
  "guidance": 4.9558,
  "doctors": 4.9558,
  "telemedicine": 4.9558,
  "appointment": 4.9558,
  "fabric": 4.2697,
  "global": 3.8712,
  "connectivity": 4.2697,
  "intelligence": 3.3742,
  "hnf": 4.2697,
  "tiers": 3.8712,
  "nodes": 3.5904,
  "topology": 4.2697,
  "handler": 4.9558,
  "processing": 4.9558,
  "webhook": 4.9558,
  "receive": 4.9558,
  "messages": 4.2697,
  "hea": 4.2697,
  "relationship": 4.9558,
  "leads": 4.9558,
  "deals": 4.9558,
  "pipeline": 4.9558,
  "storage": 3.3742,
  "list": 4.9558,
  "daily": 4.2697,
  "runner": 4.9558,
  "run": 3.3742,
  "morning": 4.9558,
  "briefing": 4.9558,
  "wat": 4.9558,
  "evening": 4.9558,
  "report": 4.9558,
  "full": 4.9558,
  "gover": 4.9558,
  "watchdog": 4.9558,
  "minutes": 4.2697,
  "last": 4.2697,
  "232ms": 4.9558,
  "24h": 4.9558,
  "30ms": 4.9558,
  "apex": 4.9558,
  "central": 4.9558,
  "nbsp": 4.2697,
  "financial": 4.9558,
  "regulator": 4.9558,
  "deposit": 4.9558,
  "borrow": 4.9558,
  "repay": 4.9558,
  "loans": 4.9558,
  "generator": 4.9558,
  "contractgen": 4.9558,
  "tool": 4.9558,
  "treasury": 4.2697,
  "tools": 4.2697,
  "concord": 4.9558,
  "security": 4.2697,
  "sovereignty": 4.9558,
  "boundary": 4.9558,
  "middot": 4.9558,
  "permanent": 4.9558,
  "document": 4.9558,
  "external": 4.9558,
  "token": 2.5455,
  "aggregated": 4.9558,
  "prism": 4.2697,
  "quidax": 4.9558,
  "actions": 4.2697,
  "sync": 4.9558,
  "balances": 4.2697,
  "generate": 4.9558,
  "btc": 4.9558,
  "power": 3.8712,
  "connecting": 4.9558,
  "quick": 4.9558,
  "search": 4.2697,
  "settings": 4.9558,
  "pool": 4.9558,
  "aggregator": 4.9558,
  "compare": 4.9558,
  "bitcoin": 4.9558,
  "pools": 4.9558,
  "find": 4.9558,
  "best": 4.9558,
  "fees": 4.2697,
  "disclaimer": 4.9558,
  "comparison": 4.9558,
  "purposes": 4.9558,
  "minimum": 4.9558,
  "payouts": 4.9558,
  "can": 4.2697,
  "change": 4.9558,
  "alway": 4.9558,
  "loyalty": 4.9558,
  "earn": 3.5904,
  "points": 4.9558,
  "members": 3.8712,
  "spent": 4.9558,
  "check": 4.2697,
  "bronze": 4.9558,
  "silver": 4.9558,
  "gold": 4.9558,
  "19k": 4.9558,
  "pla": 4.9558,
  "mesh": 2.626,
  "people": 4.9558,
  "now": 4.9558,
  "field": 3.5904,
  "frozen": 3.5904,
  "sep": 3.3742,
  "validation": 3.5904,
  "gates": 3.3742,
  "radio": 3.5904,
  "sound": 4.2697,
  "rail": 4.2697,
  "upsell": 4.9558,
  "evenue": 4.9558,
  "when": 4.9558,
  "makes": 4.9558,
  "purchase": 4.2697,
  "analyzes": 4.9558,
  "their": 4.9558,
  "action": 4.9558,
  "recommends": 4.9558,
  "next": 4.9558,
  "logical": 4.9558,
  "recommendations": 4.9558,
  "affiliates": 4.9558,
  "referral": 4.9558,
  "commission": 4.9558,
  "referrals": 4.9558,
  "affiliate": 4.2697,
  "program": 4.9558,
  "link": 4.9558,
  "share": 4.2697,
  "tracking": 4.2697,
  "licks": 4.9558,
  "track": 4.9558,
  "visit": 4.9558,
  "they": 4.9558,
  "make": 4.9558,
  "commissions": 4.9558,
  "accumulate": 4.9558,
  "cash": 4.9558,
  "out": 4.2697,
  "poi": 4.9558,
  "consensus": 4.9558,
  "stats": 3.8712,
  "layers": 3.8712,
  "zero": 3.5904,
  "gas": 4.2697,
  "approved": 4.9558,
  "rejected": 4.9558,
  "fraud": 4.9558,
  "verificat": 4.9558,
  "collector": 4.9558,
  "recently": 4.9558,
  "collected": 4.9558,
  "yet": 4.2697,
  "08028687857": 4.2697,
  "agreement": 4.9558,
  "attached": 4.9558,
  "records": 4.9558,
  "obligations": 4.9558,
  "carries": 4.9558,
  "cannot": 4.9558,
  "factory": 4.2697,
  "deployed": 4.2697,
  "creation": 4.9558,
  "flat": 4.9558,
  "erc": 4.9558,
  "pol": 4.9558,
  "transfers": 4.9558,
  "mints": 4.9558,
  "control": 4.9558,
  "supply": 4.2697,
  "parking": 4.9558,
  "burn": 4.9558,
  "five": 4.9558,
  "layer": 3.1987,
  "poly": 4.9558,
  "graduation": 4.9558,
  "pulled": 4.9558,
  "pri": 4.9558,
  "whitepaper": 4.9558,
  "tokenomics": 4.9558,
  "10m": 4.9558,
  "burned": 4.9558,
  "cashback": 4.9558,
  "eol": 4.9558,
  "fix": 4.2697,
  "quarkus": 4.9558,
  "tenant": 4.9558,
  "authorization": 4.9558,
  "bypass": 4.9558,
  "cve": 4.9558,
  "openid": 4.9558,
  "connect": 3.3742,
  "providers": 4.2697,
  "handles": 4.9558,
  "bearer": 4.9558,
  "authentication": 4.9558,
  "flow": 4.9558,
  "caching": 4.9558,
  "remote": 4.9558,
  "introsp": 4.9558,
  "started": 4.2697,
  "origin": 4.9558,
  "trials": 4.9558,
  "web": 4.9558,
  "chrome": 4.9558,
  "developersxgithubmastodonblueskyhomepage": 4.9558,
  "skip": 4.9558,
  "main": 4.2697,
  "content": 4.2697,
  "english": 4.9558,
  "deutsch": 4.9558,
  "espa": 4.9558,
  "rica": 4.9558,
  "latina": 4.9558,
  "fran": 4.9558,
  "ais": 4.9558,
  "indonesia": 4.9558,
  "italiano": 4.9558,
  "nederlands": 4.9558,
  "polski": 4.9558,
  "portugu": 4.9558,
  "brasil": 4.9558,
  "minimax": 4.9558,
  "provider": 4.2697,
  "performance": 4.2697,
  "benchmarking": 4.2697,
  "analysis": 4.2697,
  "artificial": 4.2697,
  "continue": 4.2697,
  "default": 4.2697,
  "10k": 4.2697,
  "input": 4.2697,
  "workload": 4.2697,
  "results": 3.8712,
  "other": 4.2697,
  "workloads": 4.2697,
  "historical": 4.2697,
  "longer": 4.2697,
  "updated": 3.8712,
  "has": 4.2697,
  "launched": 4.2697,
  "newer": 4.9558,
  "google": 4.9558,
  "news": 4.9558,
  "serpapi": 4.9558,
  "ted": 4.9558,
  "languages": 4.9558,
  "parameters": 4.9558,
  "topic": 4.9558,
  "parameter": 4.9558,
  "defines": 4.9558,
  "used": 4.9558,
  "accessing": 4.9558,
  "deepseek": 4.9558,
  "newe": 4.9558,
  "images": 4.9558,
  "symbol": 4.9558,
  "requests": 4.9558,
  "monthly": 4.9558,
  "tier": 4.9558,
  "support": 4.9558,
  "endp": 4.9558,
  "builders": 4.9558,
  "developers": 4.9558,
  "calls": 4.2697,
  "developer": 4.9558,
  "privacy": 4.9558,
  "signals": 4.9558,
  "sectors": 4.9558,
  "opportunities": 4.9558,
  "intel": 4.9558,
  "forecasting": 4.9558,
  "harzdm": 4.9558,
  "com": 4.2697,
  "getly": 4.9558,
  "hopping": 4.9558,
  "cart": 4.9558,
  "person": 4.9558,
  "follow": 4.9558,
  "flag": 4.9558,
  "bot": 4.9558,
  "interact": 4.9558,
  "commands": 4.9558,
  "command": 4.9558,
  "learning": 4.9558,
  "series": 4.9558,
  "complete": 4.9558,
  "practical": 4.9558,
  "computer": 4.2697,
  "skills": 4.9558,
  "beginner": 4.9558,
  "ready": 4.9558,
  "professional": 4.9558,
  "books": 4.9558,
  "chapters": 4.9558,
  "hands": 4.9558,
  "exercises": 4.9558,
  "auth": 4.9558,
  "audit": 4.9558,
  "time": 4.2697,
  "monitor": 4.9558,
  "breakdown": 4.9558,
  "produce": 4.9558,
  "slack": 4.9558,
  "memory": 4.9558,
  "channel": 4.9558,
  "like": 4.9558,
  "base44": 4.9558,
  "superagent": 4.9558,
  "but": 4.9558,
  "yours": 4.9558,
  "notification": 4.9558,
  "notify": 4.9558,
  "pending": 4.9558,
  "delivered": 4.9558,
  "subscriptions": 4.9558,
  "micro": 4.9558,
  "lending": 4.9558,
  "proper": 4.9558,
  "foreign": 4.9558,
  "converter": 4.9558,
  "convert": 4.9558,
  "fiat": 4.9558,
  "alerts": 4.9558,
  "eur": 4.9558,
  "gbp": 4.9558,
  "ghs": 4.9558,
  "social": 4.9558,
  "accounts": 4.2697,
  "posting": 4.9558,
  "together": 4.9558,
  "groups": 4.9558,
  "posts": 4.9558,
  "popular": 4.9558,
  "communities": 4.9558,
  "traders": 4.9558,
  "cryp": 4.9558,
  "certifications": 4.9558,
  "verifiable": 4.9558,
  "certificates": 4.9558,
  "courses": 4.9558,
  "exams": 4.9558,
  "taken": 4.9558,
  "take": 4.9558,
  "exam": 4.9558,
  "select": 4.2697,
  "course": 4.9558,
  "android": 3.8712,
  "magic": 4.9558,
  "automation": 4.9558,
  "deployment": 4.9558,
  "click": 4.9558,
  "push": 4.2697,
  "deployforge": 4.9558,
  "harzgit": 4.2697,
  "page": 4.9558,
  "repository": 4.9558,
  "source": 4.9558,
  "repositories": 4.9558,
  "commits": 4.9558,
  "deployments": 4.9558,
  "file": 4.9558,
  "repos": 4.9558,
  "eternity": 4.9558,
  "inheritance": 4.9558,
  "inheri": 4.9558,
  "orbital": 4.9558,
  "nasa": 4.9558,
  "cost": 4.9558,
  "location": 4.9558,
  "latitude": 4.9558,
  "longitude": 4.9558,
  "lagos": 4.9558,
  "reserve": 4.9558,
  "spot": 4.9558,
  "coming": 4.9558,
  "soon": 4.9558,
  "bringing": 4.9558,
  "vps": 4.9558,
  "databases": 4.9558,
  "kubernetes": 4.9558,
  "anywhere": 4.9558,
  "everywhere": 4.9558,
  "regions": 4.9558,
  "instances": 4.9558,
  "runtime": 4.9558,
  "edgenet": 4.9558,
  "node": 3.5904,
  "terminal": 4.9558,
  "held": 4.9558,
  "webcrypto": 4.9558,
  "non": 4.9558,
  "extractable": 4.9558,
  "knows": 4.2697,
  "what": 4.2697,
  "transport": 4.2697,
  "download": 4.2697,
  "antenna": 4.9558,
  "needed": 4.9558,
  "cell": 4.9558,
  "tower": 4.9558,
  "direct": 4.9558,
  "encrypted": 4.9558,
  "net": 4.9558,
  "hardware": 4.9558,
  "independent": 4.9558,
  "exists": 4.9558,
  "hostile": 4.9558,
  "scena": 4.9558,
  "icon": 4.2697,
  "1a237e": 4.9558,
  "sizes": 4.9558,
  "broadcast": 3.8712,
  "mass": 4.2697,
  "broadcasts": 4.9558,
  "subscribers": 4.9558,
  "empty": 4.9558,
  "bits": 4.9558,
  "sec": 4.9558,
  "text": 4.2697,
  "talk": 4.9558,
  "inbox": 4.9558,
  "closed": 4.9558,
  "loop": 4.9558,
  "round": 4.9558,
  "trip": 4.9558,
  "encodes": 4.9558,
  "rails": 4.9558,
  "testbed": 3.8712,
  "three": 4.9558,
  "lab": 3.1987,
  "usr": 4.9558,
  "bin": 4.9558,
  "env": 4.9558,
  "python3": 4.9558,
  "replicates": 4.9558,
  "apk": 4.2697,
  "frame": 4.2697,
  "relay": 4.9558,
  "logic": 4.9558,
  "separate": 4.9558,
  "hosted": 4.9558,
  "downloads": 4.9558,
  "zip": 4.9558,
  "debu": 4.9558,
  "actually": 4.9558,
  "received": 4.9558,
  "transmitted": 4.9558,
  "morse": 4.9558,
  "dits": 4.9558,
  "dit": 4.9558,
  "dah": 4.9558,
  "nft": 4.2697,
  "music": 4.9558,
  "film": 4.9558,
  "tokenized": 4.9558,
  "tokenize": 4.9558,
  "rights": 4.9558,
  "listings": 4.9558,
  "sales": 4.9558,
  "earned": 4.9558,
  "digit": 4.9558,
  "energ": 4.9558,
  "orientation": 4.9558,
  "portrait": 4.9558,
  "1a1a2e": 4.9558,
  "solar": 4.9558,
  "trading": 4.9558,
  "orders": 4.2697,
  "equipment": 4.9558,
  "quote": 4.9558,
  "type": 4.9558,
  "sol": 4.9558,
  "african": 4.9558,
  "welcome": 4.9558,
  "give": 4.9558,
  "side": 4.9558,
  "already": 4.9558,
  "have": 4.9558,
  "sky": 4.9558,
  "identity": 4.2697,
  "entity": 4.9558,
  "types": 4.9558,
  "orgs": 4.9558,
  "trust": 4.9558,
  "explainable": 4.9558,
  "domain": 4.9558,
  "scoring": 4.9558,
  "resour": 4.9558,
  "java": 4.9558,
  "mainactivity": 4.9558,
  "files": 4.9558,
  "package": 4.9558,
  "import": 4.9558,
  "annotation": 4.9558,
  "suppresslint": 4.9558,
  "rty": 4.9558,
  "mount": 4.9558,
  "mine": 4.9558,
  "speaks": 4.9558,
  "over": 4.9558,
  "worker": 4.9558,
  "answers": 4.9558,
  "ping": 4.9558,
  "pong": 4.9558,
  "inte": 4.9558,
  "fake": 4.9558,
  "sys": 4.9558,
  "urllib": 4.9558,
  "request": 4.9558,
  "parse": 4.9558,
  "base": 4.9558,
  "https": 4.9558,
  "hamzarabiu390": 4.9558,
  "dev": 4.9558,
  "who": 4.9558,
  "dotest": 4.9558,
  "rtts": 4.9558,
  "bytearray": 4.9558,
  "def": 4.9558,
  "reality": 4.9558,
  "ordinary": 4.9558,
  "form": 4.9558,
  "useful": 4.9558,
  "hop": 4.9558,
  "without": 4.9558,
  "cellular": 4.9558,
  "harness": 4.9558,
  "dpb": 4.9558,
  "persistence": 4.9558,
  "delay": 4.9558,
  "tolerant": 4.9558,
  "console": 4.9558,
  "state": 4.9558,
  "survives": 4.9558,
  "cold": 4.9558,
  "starts": 4.9558,
  "isolates": 4.9558,
  "acke": 4.9558,
  "mail": 4.9558,
  "here": 4.9558,
  "forgot": 4.9558,
  "password": 4.9558,
  "reset": 4.9558,
  "pas": 4.9558,
  "merchant": 4.9558,
  "experiment": 4.9558,
  "merchants": 4.9558,
  "measure": 4.9558,
  "gmv": 4.9558,
  "controlled": 4.9558,
  "tracker": 4.9558,
  "flywheel": 4.9558,
  "financing": 4.9558,
  "clients": 4.9558,
  "restaurant": 4.9558,
  "setup": 4.9558,
  "forms": 4.9558,
  "that": 4.9558,
  "collect": 4.9558,
  "drag": 4.9558,
  "drop": 4.9558,
  "checkbox": 4.9558,
  "fields": 4.9558,
  "integration": 4.9558,
  "harzos": 4.9558,
  "serverless": 4.9558,
  "school": 4.9558,
  "running": 4.9558,
  "servers": 4.9558,
  "pho": 4.9558
 },
 "expansion": {
  "chain": [
   "status",
   "id",
   "key"
  ],
  "explorer": [
   "add",
   "blocks",
   "chain"
  ],
  "proof": [
   "chain",
   "add",
   "admin"
  ],
  "edge": [
   "overview",
   "add",
   "blocks"
  ],
  "evm": [
   "add",
   "blocks",
   "chain"
  ],
  "compatible": [
   "add",
   "blocks",
   "chain"
  ],
  "sha": [
   "add",
   "blocks",
   "chain"
  ],
  "id": [
   "chain",
   "add",
   "api"
  ],
  "overview": [
   "edge",
   "add",
   "blocks"
  ],
  "blocks": [
   "add",
   "chain",
   "compatible"
  ],
  "transactions": [
   "add",
   "blocks",
   "chain"
  ],
  "validators": [
   "add",
   "blocks",
   "chain"
  ],
  "contracts": [
   "chain",
   "add",
   "blocks"
  ],
  "add": [
   "blocks",
   "chain",
   "compatible"
  ],
  "metamask": [
   "chain",
   "add",
   "blocks"
  ],
  "bridge": [
   "chain",
   "status",
   "api"
  ],
  "cross": [
   "api",
   "bridge",
   "chain"
  ],
  "polygon": [
   "api",
   "bridge",
   "chain"
  ],
  "status": [
   "chain",
   "bridge",
   "version"
  ],
  "operational": [
   "api",
   "bridge",
   "chain"
  ],
  "api": [
   "key",
   "account",
   "bridge"
  ],
  "key": [
   "chain",
   "api",
   "admin"
  ],
  "required": [
   "api",
   "bridge",
   "chain"
  ],
  "req": [
   "api",
   "bridge",
   "chain"
  ],
  "min": [
   "api",
   "bridge",
   "chain"
  ],
  "miner": [
   "3m",
   "9m",
   "automated"
  ],
  "cron": [
   "3m",
   "9m",
   "automated"
  ],
  "automated": [
   "3m",
   "9m",
   "balance"
  ],
  "mining": [
   "3m",
   "9m",
   "automated"
  ],
  "scheduler": [
   "3m",
   "9m",
   "automated"
  ],
  "v7": [
   "3m",
   "9m",
   "automated"
  ],
  "version": [
   "chain",
   "status",
   "3m"
  ],
  "3m": [
   "9m",
   "automated",
   "balance"
  ],
  "block": [
   "3m",
   "9m",
   "automated"
  ],
  "height": [
   "3m",
   "9m",
   "automated"
  ],
  "9m": [
   "3m",
   "automated",
   "balance"
  ],
  "balance": [
   "3m",
   "9m",
   "automated"
  ],
  "total": [
   "3m",
   "9m",
   "automated"
  ],
  "wallets": [
   "3m",
   "9m",
   "automated"
  ],
  "ecp": [
   "admin",
   "chain",
   "continuity"
  ],
  "shutdown": [
   "admin",
   "chain",
   "continuity"
  ],
  "economy": [
   "admin",
   "chain",
   "continuity"
  ],
  "economic": [
   "admin",
   "chain",
   "continuity"
  ],
  "continuity": [
   "admin",
   "chain",
   "demo"
  ],
  "protocol": [
   "only",
   "value",
   "real"
  ],
  "v0": [
   "admin",
   "chain",
   "continuity"
  ],
  "demo": [
   "admin",
   "chain",
   "continuity"
  ],
  "sandbox": [
   "admin",
   "chain",
   "continuity"
  ],
  "value": [
   "only",
   "protocol",
   "admin"
  ],
  "only": [
   "protocol",
   "value",
   "admin"
  ],
  "no": [
   "chain",
   "real",
   "money"
  ],
  "real": [
   "chain",
   "no",
   "protocol"
  ],
  "money": [
   "no",
   "admin",
   "chain"
  ],
  "settlement": [
   "admin",
   "chain",
   "continuity"
  ],
  "queued": [
   "admin",
   "chain",
   "continuity"
  ],
  "needs": [
   "admin",
   "chain",
   "continuity"
  ],
  "admin": [
   "chain",
   "continuity",
   "demo"
  ],
  "genesis": [
   "age",
   "appointments",
   "billing"
  ],
  "hospital": [
   "age",
   "appointments",
   "billing"
  ],
  "management": [
   "age",
   "appointments",
   "billing"
  ],
  "system": [
   "age",
   "appointments",
   "billing"
  ],
  "patients": [
   "age",
   "appointments",
   "billing"
  ],
  "appointments": [
   "pharmacy",
   "age",
   "billing"
  ],
  "billing": [
   "age",
   "appointments",
   "condition"
  ],
  "pharmacy": [
   "appointments",
   "age",
   "billing"
  ],
  "labs": [
   "age",
   "appointments",
   "billing"
  ],
  "staff": [
   "age",
   "appointments",
   "billing"
  ],
  "register": [
   "age",
   "appointments",
   "billing"
  ],
  "patient": [
   "age",
   "appointments",
   "billing"
  ],
  "age": [
   "appointments",
   "billing",
   "condition"
  ],
  "gender": [
   "age",
   "appointments",
   "billing"
  ],
  "male": [
   "age",
   "appointments",
   "billing"
  ],
  "female": [
   "age",
   "appointments",
   "billing"
  ],
  "phone": [
   "age",
   "appointments",
   "billing"
  ],
  "condition": [
   "age",
   "appointments",
   "billing"
  ],
  "wholesale": [
   "account",
   "api",
   "cloud"
  ],
  "cloud": [
   "wallet",
   "create",
   "you"
  ],
  "reseller": [
   "account",
   "api",
   "cloud"
  ],
  "hosting": [
   "account",
   "api",
   "cloud"
  ],
  "platform": [
   "v2",
   "account",
   "api"
  ],
  "white": [
   "account",
   "api",
   "cloud"
  ],
  "label": [
   "account",
   "api",
   "cloud"
  ],
  "sites": [
   "account",
   "api",
   "cloud"
  ],
  "wallet": [
   "cloud",
   "create",
   "account"
  ],
  "v2": [
   "platform",
   "account",
   "api"
  ],
  "pwa": [
   "account",
   "api",
   "cloud"
  ],
  "login": [
   "account",
   "api",
   "cloud"
  ],
  "sign": [
   "account",
   "api",
   "cloud"
  ],
  "up": [
   "account",
   "api",
   "cloud"
  ],
  "log": [
   "account",
   "api",
   "cloud"
  ],
  "create": [
   "cloud",
   "wallet",
   "account"
  ],
  "account": [
   "api",
   "cloud",
   "create"
  ],
  "you": [
   "cloud",
   "account",
   "api"
  ],
  "telecom": [
   "edge",
   "api",
   "app"
  ],
  "sms": [
   "api",
   "otp",
   "calling"
  ],
  "compute": [
   "api",
   "calling",
   "cloudflare"
  ],
  "world": [
   "first",
   "api",
   "edge"
  ],
  "first": [
   "world",
   "api",
   "edge"
  ],
  "operator": [
   "api",
   "calling",
   "cloudflare"
  ],
  "otp": [
   "api",
   "sms",
   "calling"
  ],
  "delivery": [
   "api",
   "calling",
   "cloudflare"
  ],
  "voice": [
   "api",
   "calling",
   "cloudflare"
  ],
  "calling": [
   "api",
   "cloudflare",
   "compute"
  ],
  "esim": [
   "api",
   "calling",
   "cloudflare"
  ],
  "cloudflare": [
   "api",
   "calling",
   "compute"
  ],
  "pops": [
   "api",
   "calling",
   "cloudflare"
  ],
  "get": [
   "api",
   "dev",
   "domain"
  ],
  "view": [
   "api",
   "calling",
   "cloudflare"
  ],
  "docs": [
   "api",
   "calling",
   "cloudflare"
  ],
  "sendcha": [
   "api",
   "calling",
   "cloudflare"
  ],
  "verify": [
   "api",
   "code",
   "fe"
  ],
  "verification": [
   "api",
   "code",
   "fe"
  ],
  "powered": [
   "ai",
   "api",
   "assistant"
  ],
  "gateway": [
   "api",
   "code",
   "fe"
  ],
  "send": [
   "api",
   "code",
   "fe"
  ],
  "number": [
   "phone",
   "api",
   "code"
  ],
  "purpose": [
   "api",
   "code",
   "fe"
  ],
  "optional": [
   "api",
   "code",
   "fe"
  ],
  "code": [
   "api",
   "fe",
   "gateway"
  ],
  "fe": [
   "api",
   "code",
   "gateway"
  ],
  "skyeye": [
   "any",
   "apps",
   "ecosystem"
  ],
  "satellite": [
   "any",
   "apps",
   "ecosystem"
  ],
  "oracle": [
   "any",
   "apps",
   "ecosystem"
  ],
  "feature": [
   "no",
   "phone",
   "any"
  ],
  "phones": [
   "phone",
   "any",
   "apps"
  ],
  "internet": [
   "any",
   "apps",
   "ecosystem"
  ],
  "apps": [
   "any",
   "ecosystem",
   "feature"
  ],
  "any": [
   "apps",
   "ecosystem",
   "feature"
  ],
  "invention": [
   "any",
   "apps",
   "ecosystem"
  ],
  "ecosystem": [
   "am",
   "any",
   "apps"
  ],
  "try": [
   "any",
   "apps",
   "ecosystem"
  ],
  "it": [
   "agreement",
   "any",
   "apps"
  ],
  "live": [
   "no",
   "token",
   "bridge"
  ],
  "ussd": [
   "any",
   "apps",
   "ecosystem"
  ],
  "simulato": [
   "any",
   "apps",
   "ecosystem"
  ],
  "workforce": [
   "agents",
   "ai",
   "categories"
  ],
  "network": [
   "revenue",
   "loading",
   "overview"
  ],
  "human": [
   "agents",
   "ai",
   "categories"
  ],
  "ai": [
   "agents",
   "assistant",
   "categories"
  ],
  "revenue": [
   "network",
   "services",
   "dev"
  ],
  "streams": [
   "agents",
   "ai",
   "categories"
  ],
  "agents": [
   "ai",
   "categories",
   "economy"
  ],
  "service": [
   "agents",
   "aggregated",
   "ai"
  ],
  "categories": [
   "agents",
   "ai",
   "economy"
  ],
  "services": [
   "loading",
   "network",
   "revenue"
  ],
  "hybrid": [
   "agents",
   "ai",
   "categories"
  ],
  "projects": [
   "agents",
   "ai",
   "categories"
  ],
  "health": [
   "get",
   "loading",
   "network"
  ],
  "assistant": [
   "ai",
   "clinics",
   "describe"
  ],
  "nigeria": [
   "ai",
   "assistant",
   "clinics"
  ],
  "triage": [
   "ai",
   "assistant",
   "clinics"
  ],
  "clinics": [
   "ai",
   "assistant",
   "describe"
  ],
  "profile": [
   "ai",
   "assistant",
   "clinics"
  ],
  "reminders": [
   "ai",
   "assistant",
   "clinics"
  ],
  "symptom": [
   "ai",
   "assistant",
   "clinics"
  ],
  "describe": [
   "ai",
   "assistant",
   "clinics"
  ],
  "symptoms": [
   "ai",
   "assistant",
   "clinics"
  ],
  "instant": [
   "ai",
   "assistant",
   "clinics"
  ],
  "guidance": [
   "ai",
   "assistant",
   "clinics"
  ],
  "healthcare": [
   "appointment",
   "appointments",
   "book"
  ],
  "loading": [
   "network",
   "services",
   "balances"
  ],
  "doctors": [
   "appointment",
   "appointments",
   "book"
  ],
  "telemedicine": [
   "appointment",
   "appointments",
   "book"
  ],
  "book": [
   "appointment",
   "appointments",
   "doctors"
  ],
  "appointment": [
   "appointments",
   "book",
   "doctors"
  ],
  "daily": [
   "am",
   "automated",
   "briefing"
  ],
  "runner": [
   "am",
   "automated",
   "briefing"
  ],
  "reports": [
   "am",
   "automated",
   "briefing"
  ],
  "run": [
   "am",
   "automated",
   "briefing"
  ],
  "morning": [
   "am",
   "automated",
   "briefing"
  ],
  "briefing": [
   "am",
   "automated",
   "daily"
  ],
  "am": [
   "automated",
   "briefing",
   "daily"
  ],
  "wat": [
   "am",
   "automated",
   "briefing"
  ],
  "evening": [
   "am",
   "automated",
   "briefing"
  ],
  "pm": [
   "am",
   "automated",
   "briefing"
  ],
  "report": [
   "am",
   "automated",
   "briefing"
  ],
  "full": [
   "am",
   "automated",
   "briefing"
  ],
  "token": [
   "live",
   "endpoints",
   "no"
  ],
  "treasury": [
   "aggregated",
   "bridge",
   "chain"
  ],
  "description": [
   "aggregated",
   "bridge",
   "chain"
  ],
  "aggregated": [
   "bridge",
   "chain",
   "description"
  ],
  "from": [
   "bridge",
   "live",
   "real"
  ],
  "prism": [
   "endpoints",
   "live",
   "token"
  ],
  "endpoints": [
   "live",
   "prism",
   "token"
  ],
  "storage": [
   "aggregated",
   "bridge",
   "chain"
  ],
  "quidax": [
   "actions",
   "address",
   "balances"
  ],
  "eth": [
   "actions",
   "address",
   "balances"
  ],
  "usdt": [
   "actions",
   "address",
   "balances"
  ],
  "actions": [
   "address",
   "balances",
   "bridge"
  ],
  "sync": [
   "actions",
   "address",
   "balances"
  ],
  "balances": [
   "loading",
   "actions",
   "address"
  ],
  "generate": [
   "actions",
   "address",
   "balances"
  ],
  "new": [
   "actions",
   "address",
   "balances"
  ],
  "btc": [
   "actions",
   "address",
   "balances"
  ],
  "address": [
   "actions",
   "balances",
   "bridge"
  ],
  "digital": [
   "wallet",
   "actions",
   "address"
  ],
  "v1": [
   "actions",
   "address",
   "balances"
  ],
  "power": [
   "actions",
   "address",
   "balances"
  ],
  "affiliates": [
   "affiliate",
   "commission",
   "ea"
  ],
  "earn": [
   "affiliate",
   "affiliates",
   "commission"
  ],
  "per": [
   "affiliate",
   "affiliates",
   "commission"
  ],
  "referral": [
   "affiliate",
   "affiliates",
   "commission"
  ],
  "commission": [
   "affiliate",
   "affiliates",
   "ea"
  ],
  "every": [
   "protocol",
   "affiliate",
   "affiliates"
  ],
  "members": [
   "affiliate",
   "affiliates",
   "commission"
  ],
  "referrals": [
   "affiliate",
   "affiliates",
   "commission"
  ],
  "paid": [
   "affiliate",
   "affiliates",
   "commission"
  ],
  "join": [
   "affiliate",
   "affiliates",
   "commission"
  ],
  "affiliate": [
   "affiliates",
   "commission",
   "ea"
  ],
  "program": [
   "affiliate",
   "affiliates",
   "commission"
  ],
  "link": [
   "affiliate",
   "affiliates",
   "commission"
  ],
  "share": [
   "affiliate",
   "affiliates",
   "commission"
  ],
  "ea": [
   "affiliate",
   "affiliates",
   "commission"
  ],
  "contract": [
   "agreement",
   "attached",
   "be"
  ],
  "forge": [
   "agreement",
   "attached",
   "be"
  ],
  "agreement": [
   "attached",
   "be",
   "cannot"
  ],
  "into": [
   "agreement",
   "attached",
   "be"
  ],
  "zero": [
   "agreement",
   "attached",
   "be"
  ],
  "attached": [
   "agreement",
   "be",
   "cannot"
  ],
  "records": [
   "agreement",
   "attached",
   "be"
  ],
  "obligations": [
   "agreement",
   "attached",
   "be"
  ],
  "carries": [
   "agreement",
   "attached",
   "be"
  ],
  "cannot": [
   "agreement",
   "attached",
   "be"
  ],
  "be": [
   "agreement",
   "attached",
   "cannot"
  ],
  "tr": [
   "agreement",
   "attached",
   "be"
  ],
  "super": [
   "chain",
   "cloud",
   "wallet"
  ],
  "app": [
   "edge",
   "field",
   "frozen"
  ],
  "validation": [
   "app",
   "edge",
   "field"
  ],
  "gates": [
   "app",
   "edge",
   "field"
  ],
  "mesh": [
   "protocol",
   "phone",
   "test"
  ],
  "g1": [
   "app",
   "edge",
   "field"
  ],
  "g2": [
   "app",
   "edge",
   "field"
  ],
  "field": [
   "app",
   "edge",
   "frozen"
  ],
  "frozen": [
   "app",
   "edge",
   "field"
  ],
  "sep": [
   "app",
   "edge",
   "field"
  ],
  "g3": [
   "app",
   "edge",
   "field"
  ],
  "test": [
   "mesh",
   "protocol",
   "v1"
  ],
  "testbed": [
   "frame",
   "lab",
   "mesh"
  ],
  "node": [
   "frame",
   "lab",
   "mesh"
  ],
  "py": [
   "frame",
   "lab",
   "mesh"
  ],
  "lab": [
   "frame",
   "mesh",
   "node"
  ],
  "frame": [
   "lab",
   "mesh",
   "node"
  ],
  "domain": [
   "dev",
   "hosted",
   "workers"
  ],
  "one": [
   "phone"
  ],
  "hosted": [
   "dev",
   "domain",
   "workers"
  ],
  "workers": [
   "dev",
   "domain",
   "hosted"
  ],
  "dev": [
   "domain",
   "hosted",
   "workers"
  ],
  "hamzarabiu390": [
   "dev",
   "domain",
   "hosted"
  ]
 },
 "expansion_weight": 0.4,
 "thresholds": {
  "answer": 0.16,
  "sentence": 0.28
 },
 "bands": {
  "high": 0.216,
  "medium": 0.16
 },
 "relevance_threshold": 0.16,
 "confidence_bands": {
  "high": 0.216,
  "medium": 0.16
 },
 "sentiment_lexicon": {
  "positive": [
   "love",
   "great",
   "magnificent",
   "excellent",
   "happy",
   "strong",
   "reliable",
   "fast",
   "beautiful",
   "amazing",
   "secure",
   "proud",
   "win",
   "success"
  ],
  "negative": [
   "failed",
   "fail",
   "lost",
   "crash",
   "crashed",
   "broken",
   "slow",
   "angry",
   "bad",
   "terrible",
   "scam",
   "fraud",
   "down",
   "error"
  ]
 }
};
