// HARZ Gateway v1.0 — the public Internet doorway into .harz
// Per Root v2 FROZEN v1.0, build task 3 (gateway fabric, software proof).
// The gateway TRANSLATES worlds: public form (pay.harz.ng) ↔ canonical form (pay.harz).
// The canonical identity REMAINS pay.harz — harz.ng is the doorway, never the replacement.
// Runs on any substrate (Node CLI/serve, Worker, browser) — software-defined, zero deps.
//
// Mapping law (deterministic, 1:1):
//   pay.harz      ↔ pay.harz.ng      (label + .harz.ng suffix)
//   pay.harz.ng  → strip suffix     → pay.harz
// Only [a-z0-9-] labels are legal in both forms. No exceptions, no aliases.

(function (root, factory) {
  const api = factory(root);
  if (typeof module !== "undefined" && module.exports) module.exports = api;
  else root.HarzGateway = api;
})(typeof self !== "undefined" ? self : this, function (root) {

  const PUBLIC_SUFFIX = ".harz.ng";
  const LABEL_RE = /^[a-z0-9-]+$/;

  // ---------- deterministic name translation ----------
  function toPublic(name) {   // pay.harz → pay.harz.ng
    let n = String(name || "").trim().toLowerCase();
    if (n.endsWith(".")) n = n.slice(0, -1);
    if (!n.endsWith(".harz")) return null;
    if (n.startsWith(".")) return null;
    const labels = n.split(".");
    for (const l of labels) if (!LABEL_RE.test(l)) return null;
    return n.slice(0, -".harz".length) + PUBLIC_SUFFIX; // pay.harz → pay + .harz.ng
  }
  function toCanonical(name) { // pay.harz.ng → pay.harz  |  pay.harz → pay.harz (idempotent)
    let n = String(name || "").trim().toLowerCase();
    if (n.endsWith(".")) n = n.slice(0, -1);
    if (n.endsWith(PUBLIC_SUFFIX)) {
      const base = n.slice(0, -PUBLIC_SUFFIX.length);
      const labels = base.split(".");
      for (const l of labels) if (!LABEL_RE.test(l)) return null;
      return base + ".harz";
    }
    if (n.endsWith(".harz")) {
      const labels = n.split(".");
      for (const l of labels) if (!LABEL_RE.test(l)) return null;
      return n;
    }
    return null; // not a HARZ name in either form
  }

  // ---------- gateway over the ONE resolver engine ----------
  // createGateway(resolverEngine) — engine loaded with a verified v2 zone.
  function createGateway(engine) {
    if (!engine) throw new Error("gateway requires a loaded resolver engine (fail-closed)");

    // resolve through the doorway: accepts BOTH forms; canonical stays canonical.
    function resolve(queryName, opts) {
      const canonical = toCanonical(queryName);
      if (!canonical) return { error: "NOT_A_HARZ_NAME", query: queryName };
      let r;
      try { r = engine.resolve(canonical, opts); }
      catch (e) { return { error: "REFUSED", reason: e.message }; } // fail-closed propagates
      if (!r) return { found: false, verdict: "NXDOMAIN", canonical, query: queryName }; // honest
      // doorway answer: canonical identity + public form + resolved endpoints
      return Object.assign({}, r, {
        canonical_name: r.name,               // pay.harz — THE identity, unchanged
        public_form: toPublic(r.name),        // pay.harz.ng — the doorway spelling
        queried_as: queryName
      });
    }

    // ---------- public mirror zone generation ----------
    // The artifact that WILL be uploaded when harz.ng exists: a real DNS zone file
    // mapping every name's public form to its https endpoint (CNAME to target host).
    function generatePublicMirrorZone(opts) {
      const zone = engine.getZone();
      if (!zone) throw new Error("no zone loaded");
      const lines = [
        "; HARZ PUBLIC MIRROR ZONE — generated by harz-gateway v1.0",
        "; source: canonical .harz zone (height " + zone.height + ") — ONE book, this is a projection",
        "; law: canonical identity remains <name>.harz; this mirror is the public doorway only",
        "$ORIGIN harz.ng.",
        "@            3600 IN SOA ns1.harz.ng. hostmaster.harz.ng. (" + zone.height + " 3600 600 86400 300)",
        "@            3600 IN NS  ns1.harz.ng.",
        "ns1          3600 IN A   192.0.2.1 ; placeholder — real IP when harz.ng is owned"
      ];
      let count = 0, reserved = 0;
      for (const rec of zone.records) {
        const pub = toPublic(rec.name);
        if (!pub) continue;
        const host = pub.slice(0, -PUBLIC_SUFFIX.length); // pay
        if (rec.endpoints.https) {
          // CNAME to the target's host (deterministic doorway to the live endpoint)
          let target = "(none)";
          try { target = new URL(rec.endpoints.https).hostname; } catch (e) {}
          lines.push(host.padEnd(12) + " 3600 IN CNAME " + target + ".");
          count++;
        } else {
          // honest reserved: no fabrication — an explanatory TXT instead of a fake CNAME
          lines.push(host.padEnd(12) + ' 3600 IN TXT "reserved — no live endpoint in canonical zone"');
          reserved++;
        }
      }
      const text = lines.join("\n") + "\n";
      return { text, cname_count: count, reserved_count: reserved, origin: "harz.ng." };
    }

    return { resolve, toPublic, toCanonical, generatePublicMirrorZone, engine };
  }

  return { createGateway, toPublic, toCanonical };
});

// ================= Node projection: CLI + HTTP doorway server =================
if (typeof require !== "undefined" && typeof module !== "undefined" && require.main === module) {
  const fs = require("fs");
  const api = module.exports;
  const Resolver = require("../resolver/harz-resolver.js");
  const args = process.argv.slice(2);
  const cmd = args[0];

  function boot(zonePath) {
    const zoneObj = JSON.parse(fs.readFileSync(zonePath, "utf8"));
    const engine = Resolver.createEngine({ verify: Resolver.nodeVerifier() });
    const meta = engine.loadZone(zoneObj); // fail-closed: tampered zone throws here
    const gateway = api.createGateway(engine);
    return { engine, gateway, meta };
  }

  if (cmd === "resolve") {
    let zonePath = null, name = null;
    for (let i = 1; i < args.length; i++) {
      if (args[i] === "--zone") zonePath = args[++i];
      else if (!name) name = args[i];
    }
    try {
      const { gateway } = boot(zonePath);
      console.log(JSON.stringify(gateway.resolve(name)));
    } catch (e) { console.error(e.message); process.exit(3); }
  }

  if (cmd === "mirror") {
    let zonePath = null, out = null;
    for (let i = 1; i < args.length; i++) {
      if (args[i] === "--zone") zonePath = args[++i];
      if (args[i] === "--out") out = args[++i];
    }
    try {
      const { gateway } = boot(zonePath);
      const m = gateway.generatePublicMirrorZone();
      if (out) fs.writeFileSync(out, m.text);
      else process.stdout.write(m.text);
      console.error(`mirror: ${m.cname_count} CNAME + ${m.reserved_count} honest reserved records → ${out || "stdout"}`);
    } catch (e) { console.error(e.message); process.exit(3); }
  }

  if (cmd === "serve") {
    let zonePath = null, port = 8990;
    for (let i = 1; i < args.length; i++) {
      if (args[i] === "--zone") zonePath = args[++i];
      if (args[i] === "--port") port = parseInt(args[++i], 10);
    }
    let gateway;
    try { const b = boot(zonePath); gateway = b.gateway; console.error("gateway doorway serving on :" + port + " (zone: " + JSON.stringify(b.meta) + ")"); }
    catch (e) { console.error(e.message); process.exit(3); }
    const http = require("http");
    http.createServer((req, res) => {
      const u = new URL(req.url, "http://localhost");
      const send = (code, obj) => { res.writeHead(code, { "Content-Type": "application/json", "Access-Control-Allow-Origin": "*" }); res.end(JSON.stringify(obj)); };
      if (u.pathname === "/mirror") return send(200, gateway.generatePublicMirrorZone());
      if (u.pathname === "/resolve" || u.pathname === "/doh") {
        const name = u.searchParams.get("name");
        if (!name) return send(400, { error: "missing ?name" });
        const r = gateway.resolve(name);
        if (r.error === "REFUSED") return send(503, r);            // fail-closed doorway
        if (r.error === "NOT_A_HARZ_NAME") return send(400, r);
        if (!r.found) {
          if (u.pathname === "/doh") return send(200, Resolver.toDohJSON(null, name));
          return send(404, r);
        }
        if (u.pathname === "/doh") return send(200, Resolver.toDohJSON(r, name));
        return send(200, r);
      }
      send(404, { error: "routes: /resolve /doh /mirror" });
    }).listen(port, () => console.error("ready"));
  }
}
