#!/usr/bin/env python3
"""
HARZ-Reasoner-1 — TRAINING PIPELINE (v1.0)
Owner: HARZ. Trains from scratch on HARZ-owned data. No external base model.

Inputs : training-corpus.json  (HARZ Search index harvest, HARZ-owned content)
Output : reasoner1-weights.js  (embedded weights module for the harz_local adapter)
         reasoner1-weights.json (same weights, human-readable, with digests)

What this pipeline genuinely produces:
  - vocabulary with IDF term weights (trained on the HARZ corpus)
  - stopword list (statistically derived)
  - HARZ-authored sentiment lexicon (config, hand-authored, documented)
  - relevance threshold derived from corpus statistics (design-time, formula below)

What it is NOT:
  - not a fine-tune of any external model. No external weights, code or secrets.
  - not a neural network. It is a small statistical extractive reasoning model.
"""
import json, hashlib, math, statistics

corpus = json.load(open('training-corpus.json', encoding='utf-8'))
docs = corpus['documents']
N = len(docs)
dataset_digest = open('dataset-digest.txt').read().strip()

def tokens(text):
    return [t for t in ''.join(c if c.isalnum() else ' ' for c in text.lower()).split() if len(t) > 1]

# --- document frequency + IDF ---
df = {}
doc_tokens = []
for d in docs:
    toks = set(tokens((d['title'] or '') + ' ' + (d['snippet'] or '')))
    doc_tokens.append(toks)
    for t in toks:
        df[t] = df.get(t, 0) + 1

idf = {t: math.log(N / dfreq) for t, dfreq in df.items() if dfreq > 0}

# --- stopwords: appear in >= 40% of docs (statistically non-discriminative) ---
stopwords = sorted([t for t, f in df.items() if f >= 0.40 * N])

# --- relevance threshold: corpus-derived formula (frozen at design time) ---
# median IDF-cosine between each doc's title terms and its own snippet terms,
# halved. Deterministic, derived only from corpus statistics, never tuned on results.
def cos(a, b):
    ta, tb = tokens(a), tokens(b)
    if not ta or not tb: return 0.0
    wa = {t: idf.get(t, 0) for t in ta}
    wb = {t: idf.get(t, 0) for t in tb}
    na = math.sqrt(sum(v * v for v in wa.values())) or 1
    nb = math.sqrt(sum(v * v for v in wb.values())) or 1
    dot = sum(w * wb.get(t, 0) for t, w in wa.items())
    return dot / (na * nb)

title_snippet = [cos(d['title'] or '', d['snippet'] or '') for d in docs if d['title'] and d['snippet']]
threshold = round(statistics.median(title_snippet) / 2, 4)

# --- HARZ-authored sentiment lexicon (hand-authored config, documented as such) ---
sentiment = {
    "positive": ["love", "great", "good", "fast", "best", "own", "success", "working", "healthy", "win", "excellent", "verified", "live", "approved"],
    "negative": ["fail", "failed", "lost", "broken", "error", "down", "scam", "hate", "bad", "dead", "stuck", "rejected", "drained", "blocked"]
}

# --- confidence bands (design-time, derived from threshold) ---
confidence = {"high": round(threshold * 3, 4), "medium": threshold}

weights = {
    "model": "HARZ-Reasoner-1",
    "version": "1.0.0",
    "trained_at": "2026-09-24T11:10:00Z",
    "base_model": "none — trained from scratch by HARZ on HARZ-owned data",
    "algorithm": "IDF-weighted extractive reasoning over evidence units",
    "dataset": {
        "name": "HARZ Search index harvest (HARZ ecosystem content)",
        "documents": N,
        "seed_queries": corpus['seed_queries'],
        "digest_sha256": dataset_digest,
        "license": "HARZ internal corpus — HARZ-owned content crawled by HARZ Search"
    },
    "vocab_size": len(idf),
    "idf": idf,
    "stopwords": stopwords,
    "sentiment_lexicon": sentiment,
    "relevance_threshold": threshold,
    "confidence_bands": confidence,
    "training_code": "train-reasoner-1.py",
    "runtime": "harz_local adapter in harz-intelligence worker (Cloudflare Workers JS isolate)"
}

# weights digest (of the model-relevant content, sorted)
core = json.dumps({k: weights[k] for k in ('idf','stopwords','sentiment_lexicon','relevance_threshold','confidence_bands')}, sort_keys=True)
weights['weights_digest_sha256'] = hashlib.sha256(core.encode()).hexdigest()

with open('reasoner1-weights.json', 'w', encoding='utf-8') as f:
    json.dump(weights, f, ensure_ascii=False, indent=1)

with open('reasoner1-weights.js', 'w', encoding='utf-8') as f:
    f.write("// HARZ-Reasoner-1 weights — generated by train-reasoner-1.py\n")
    f.write("// dataset digest: " + dataset_digest + " | weights digest: " + weights['weights_digest_sha256'] + "\n")
    f.write("export default " + json.dumps(weights, ensure_ascii=False) + ";\n")

print("vocab size:", len(idf))
print("stopwords:", len(stopwords), stopwords[:12])
print("threshold:", threshold)
print("weights digest:", weights['weights_digest_sha256'])
