import { readFileSync, writeFileSync } from 'fs';
import { train } from './trainer.js';
import { sha256Hex } from './hash.js';
const dataset = JSON.parse(readFileSync('./train-v1.json', 'utf8'));
const corpusStats = JSON.parse(readFileSync('./corpus-stats.json', 'utf8'));
const run = train({ dataset, corpusStats });
// emit weights as a committed module (frozen artifact)
const w = JSON.stringify(run.weights, null, 1);
writeFileSync('../reasoner12-weights.js',
  '// HARZ-Reasoner-1.2 weights — generated by trainer.js run ' + run.run_id + '\n' +
  '// dataset HARZ-TRAIN-v1.0 digest ' + run.dataset_digest + ' | weights digest ' + run.weights_digest + '\n' +
  '// DO NOT hand-edit: regenerate via learning/train-1-2.mjs\n' +
  'export default ' + w + ';\n');
const { weights, ...record } = run;
writeFileSync('./run-1-2.json', JSON.stringify({ ...record, weights_digest: run.weights_digest }, null, 1));
console.log('run:', run.run_id, '| weights digest:', run.weights_digest.slice(0, 12));
console.log('train metrics:', JSON.stringify(run.train_metrics));
